### ISSUE TITLE
docs: rewrite `part-bench` doc

### ISSUE THREAD

**Issue by SebastienMorais** [LIHPC-Computational-Geometry/coupe#216]
Seems like `part-bench`'s doc is a straight copy paste from `mesh-part`.

**Comment by hhirtz** [comment]
Yes, they share the same man page because usage is very similar. :) The options specific to one of both tools are at the bottom of the `OPTIONS` section.

FYI, github renders `.scd` files as markdown files but it's incorrect. To view these files in a proper way I suggest use bash and scdoc:

```
apt install scdoc
man <(scdoc <tools/doc/part-bench.1.scd)
```

**Comment by hhirtz** [comment]
Alternatively, you can read them in a web browser with

```
scdoc <tools/doc/part-bench.1.scd | groff -mandoc -Thtml >/tmp/part-bench.html
firefox /tmp/part-bench.html
```
