### ISSUE TITLE
Robust conversion of weights from floating point to integer

### ISSUE THREAD

**Issue by cedricchevalier19** [LIHPC-Computational-Geometry/coupe#220]
For Metis and Scotch, related to #219.

Cast from floating point to integer can cause the following problems:
 - overflow if weights are highs. Ideally the sums of all the weights should fit weight type
 - zero weight are not properly supported when doing mono-criteria partitioning.

Arcane already has these kind of "smart" conversion: 
```C++
    m_zoomfactor[0] = (m_maxAllowed-m_sum[ncon])/(m_sum[0]+1);
```
https://github.com/arcaneframework/framework/blob/fd8a069bc6253a52d86019c75c78085f48ffea2f/arcane/src/arcane/std/PartitionConverter.h#L108

**Comment by hhirtz** [comment]
Indeed, metis segfaults on zeroes, and scotch seems to spin eternally. :(
