### ISSUE TITLE
Fiduccia Mattheyse doesn't support partitioning into more than two parts

### ISSUE THREAD

**Issue by msalib** [LIHPC-Computational-Geometry/coupe#304]
The docs for FM say:
```
This implementation is an extension of the original algorithm to handle partitioning into more than two parts.
```

But if you set any value of the `partition` vector to a value greater than one, you'll get a `BiPartitioningOnly` error.

**Comment by hhirtz** [comment]
Good catch! Thanks for the report. coupe could implement extensions for FM but in the meantime I'll update the docs.
